
[package]
name = "php_in_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tera = "1.12.0"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4"
serde_json = "1.0.132"

